[phases.setup]
aptPkgs = ['libpq-dev']

[phases.install]
cmds = [
  'install-php-extensions pdo_pgsql pgsql',
  'composer install --optimize-autoloader --no-scripts --no-interaction'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t server/public'