<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260221031535 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE call_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, phone_number VARCHAR(20) NOT NULL, status VARCHAR(50) NOT NULL, note TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, appelant_id INT DEFAULT NULL, handled_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D663C42EB0DD082D ON call_log (appelant_id)');
        $this->addSql('CREATE INDEX IDX_D663C42EFE65AF40 ON call_log (handled_by_id)');
        $this->addSql('ALTER TABLE call_log ADD CONSTRAINT FK_D663C42EB0DD082D FOREIGN KEY (appelant_id) REFERENCES appelant (id)');
        $this->addSql('ALTER TABLE call_log ADD CONSTRAINT FK_D663C42EFE65AF40 FOREIGN KEY (handled_by_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE call_log DROP CONSTRAINT FK_D663C42EB0DD082D');
        $this->addSql('ALTER TABLE call_log DROP CONSTRAINT FK_D663C42EFE65AF40');
        $this->addSql('DROP TABLE call_log');
    }
}
