<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260215181912 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE appelant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, lastname VARCHAR(255) NOT NULL, firstname VARCHAR(255) DEFAULT NULL, phone VARCHAR(20) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B08403B444F97DD ON appelant (phone)');
        $this->addSql('CREATE TABLE appelant_client (appelant_id INT NOT NULL, client_id INT NOT NULL, PRIMARY KEY (appelant_id, client_id))');
        $this->addSql('CREATE INDEX IDX_B737DB70B0DD082D ON appelant_client (appelant_id)');
        $this->addSql('CREATE INDEX IDX_B737DB7019EB6921 ON appelant_client (client_id)');
        $this->addSql('ALTER TABLE appelant_client ADD CONSTRAINT FK_B737DB70B0DD082D FOREIGN KEY (appelant_id) REFERENCES appelant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE appelant_client ADD CONSTRAINT FK_B737DB7019EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE appelant_client DROP CONSTRAINT FK_B737DB70B0DD082D');
        $this->addSql('ALTER TABLE appelant_client DROP CONSTRAINT FK_B737DB7019EB6921');
        $this->addSql('DROP TABLE appelant');
        $this->addSql('DROP TABLE appelant_client');
    }
}
